### ISSUE TITLE
GitHub Page for project

### ISSUE THREAD

**Issue by rainsworth** [rainsworth/ROSA#3]
We need to set up a GitHub webpage as a project prototype for MozFest.

**Comment by rainsworth** [comment]
Can be simple to begin with, e.g. set up like the [Mozilla Open Leadership Training Series](https://mozilla.github.io/open-leadership-training-series/) (GitHub: https://github.com/mozilla/open-leadership-training-series)

**Comment by acabunoc** [comment]
Let me know if you need any help deciphering what I did there :)

**Comment by drashti4** [comment]
I found [this](http://jekyllmaterialize.panoramedia.it/) and hyde theme really cool. Let me know your views :)
